[package]
name = "process-records"
version = "0.1.0"
authors = ["slipdawg <69774592+slipdawg@users.noreply.github.com>"]
edition = "2018"

[dependencies]
algorithm = { path = "../../algorithm" }
